// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Specs.EndToEnd.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Create customer")]
    public partial class CreateCustomerFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateNewCustomer.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Create customer", "In order to keep track of the different customer we have been at\nAs an Avega Coac" +
                    "h\nI want to be able to create a new customer", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("there are no customers named \'Testing Inc.\' in the database");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Navigate to the new customer page")]
        public virtual void NavigateToTheNewCustomerPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigate to the new customer page", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("I am on the \'Customers\' page");
#line 11
 testRunner.When("I click the \'Create New\' link");
#line 12
 testRunner.Then("I should be on the \'Create Customer\' page");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating new customer without validation errors")]
        public virtual void CreatingNewCustomerWithoutValidationErrors()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating new customer without validation errors", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("I am on the \'Create Customer\' page");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Contact"});
            table1.AddRow(new string[] {
                        "Testing Inc.",
                        "demon@testinc.com"});
#line 16
 testRunner.When("I create the following customer", ((string)(null)), table1);
#line 19
 testRunner.Then("I should be on the \'Customers\' page");
#line 20
  testRunner.And("a customer named \'Testing Inc.\' should be in the customer list");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating new customer with no name should give validation error")]
        public virtual void CreatingNewCustomerWithNoNameShouldGiveValidationError()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating new customer with no name should give validation error", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I am on the \'Create Customer\' page");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Contact"});
            table2.AddRow(new string[] {
                        "",
                        "demon@testinc.com"});
#line 24
 testRunner.When("I create the following customer", ((string)(null)), table2);
#line 27
 testRunner.Then("a validation error for \'Name\' should be displayed");
#line 28
  testRunner.And("I should still be on the \'Create Customer\' page");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating new customer with no email should give validation error")]
        public virtual void CreatingNewCustomerWithNoEmailShouldGiveValidationError()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating new customer with no email should give validation error", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I am on the \'Create Customer\' page");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Contact"});
            table3.AddRow(new string[] {
                        "Testing Inc",
                        ""});
#line 32
 testRunner.When("I create the following customer", ((string)(null)), table3);
#line 35
 testRunner.Then("a validation error for \'Contact\' should be displayed");
#line 36
  testRunner.And("I should still be on the \'Create Customer\' page");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
